// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8787' | (string & {});
};

export type GetApiHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetApiHealthResponses = {
    /**
     * Standard response for successful HTTP requests.
     */
    200: {
        timestamp: string;
    };
};

export type GetApiHealthResponse = GetApiHealthResponses[keyof GetApiHealthResponses];
