// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zGetApiHealthData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Standard response for successful HTTP requests.
 */
export const zGetApiHealthResponse = z.object({
    timestamp: z.iso.datetime()
});
